package network.optimize.tool.mapper;

import java.util.List;

import network.optimize.tool.entity.RoleAuth;
import network.optimize.tool.entity.RoleAuthExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    long countByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int deleteByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insert(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int insertSelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    List<RoleAuth> selectByExample(RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    RoleAuth selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleAuth record, @Param("example") RoleAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleAuth record);
}