package network.optimize.tool.mapper;

import java.util.List;

import network.optimize.tool.entity.TaskParam;
import network.optimize.tool.entity.TaskParamExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaskParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    long countByExample(TaskParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int deleteByExample(TaskParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int insert(TaskParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int insertSelective(TaskParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    List<TaskParam> selectByExample(TaskParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    TaskParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskParam record, @Param("example") TaskParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskParam record, @Param("example") TaskParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_param
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskParam record);
}