package network.optimize.tool.mapper;

import java.util.List;

import network.optimize.tool.entity.TaskFile;
import network.optimize.tool.entity.TaskFileExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TaskFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    long countByExample(TaskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int deleteByExample(TaskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int insert(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int insertSelective(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    List<TaskFile> selectByExample(TaskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    TaskFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskFile record, @Param("example") TaskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskFile record, @Param("example") TaskFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskFile record);
}