package network.optimize.tool.entity;

public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.auth_code
     *
     * @mbg.generated
     */
    private String authCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth.auth_name
     *
     * @mbg.generated
     */
    private String authName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.id
     *
     * @return the value of auth.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.id
     *
     * @param id the value for auth.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.auth_code
     *
     * @return the value of auth.auth_code
     *
     * @mbg.generated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.auth_code
     *
     * @param authCode the value for auth.auth_code
     *
     * @mbg.generated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth.auth_name
     *
     * @return the value of auth.auth_name
     *
     * @mbg.generated
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth.auth_name
     *
     * @param authName the value for auth.auth_name
     *
     * @mbg.generated
     */
    public void setAuthName(String authName) {
        this.authName = authName;
    }
}