package network.optimize.tool.entity;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_type_id
     *
     * @mbg.generated
     */
    private Long fileTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.task_id
     *
     * @return the value of file.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.task_id
     *
     * @param taskId the value for file.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_type_id
     *
     * @return the value of file.file_type_id
     *
     * @mbg.generated
     */
    public Long getFileTypeId() {
        return fileTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_type_id
     *
     * @param fileTypeId the value for file.file_type_id
     *
     * @mbg.generated
     */
    public void setFileTypeId(Long fileTypeId) {
        this.fileTypeId = fileTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.position
     *
     * @return the value of file.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.position
     *
     * @param position the value for file.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position;
    }
}