package network.optimize.tool.entity;

public class FileType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_type.file_type_name
     *
     * @mbg.generated
     */
    private String fileTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.id
     *
     * @return the value of file_type.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.id
     *
     * @param id the value for file_type.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_type.file_type_name
     *
     * @return the value of file_type.file_type_name
     *
     * @mbg.generated
     */
    public String getFileTypeName() {
        return fileTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_type.file_type_name
     *
     * @param fileTypeName the value for file_type.file_type_name
     *
     * @mbg.generated
     */
    public void setFileTypeName(String fileTypeName) {
        this.fileTypeName = fileTypeName;
    }
}