package network.optimize.tool.entity;

public class Parameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.task_type_id
     *
     * @mbg.generated
     */
    private Long taskTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.param_code
     *
     * @mbg.generated
     */
    private String paramCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.param_name
     *
     * @mbg.generated
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parameter.default_value
     *
     * @mbg.generated
     */
    private String defaultValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.id
     *
     * @return the value of parameter.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.id
     *
     * @param id the value for parameter.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.task_type_id
     *
     * @return the value of parameter.task_type_id
     *
     * @mbg.generated
     */
    public Long getTaskTypeId() {
        return taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.task_type_id
     *
     * @param taskTypeId the value for parameter.task_type_id
     *
     * @mbg.generated
     */
    public void setTaskTypeId(Long taskTypeId) {
        this.taskTypeId = taskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.param_code
     *
     * @return the value of parameter.param_code
     *
     * @mbg.generated
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.param_code
     *
     * @param paramCode the value for parameter.param_code
     *
     * @mbg.generated
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.param_name
     *
     * @return the value of parameter.param_name
     *
     * @mbg.generated
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.param_name
     *
     * @param paramName the value for parameter.param_name
     *
     * @mbg.generated
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parameter.default_value
     *
     * @return the value of parameter.default_value
     *
     * @mbg.generated
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parameter.default_value
     *
     * @param defaultValue the value for parameter.default_value
     *
     * @mbg.generated
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }
}