package network.optimize.tool.entity;

public class RoleAuth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.role_id
     *
     * @mbg.generated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_auth.auth_id
     *
     * @mbg.generated
     */
    private Long authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.id
     *
     * @return the value of role_auth.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.id
     *
     * @param id the value for role_auth.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.role_id
     *
     * @return the value of role_auth.role_id
     *
     * @mbg.generated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.role_id
     *
     * @param roleId the value for role_auth.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_auth.auth_id
     *
     * @return the value of role_auth.auth_id
     *
     * @mbg.generated
     */
    public Long getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_auth.auth_id
     *
     * @param authId the value for role_auth.auth_id
     *
     * @mbg.generated
     */
    public void setAuthId(Long authId) {
        this.authId = authId;
    }
}