package network.optimize.tool.entity;

public class TaskFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_file.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_file.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_file.file_id
     *
     * @mbg.generated
     */
    private Long fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_file.id
     *
     * @return the value of task_file.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_file.id
     *
     * @param id the value for task_file.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_file.task_id
     *
     * @return the value of task_file.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_file.task_id
     *
     * @param taskId the value for task_file.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_file.file_id
     *
     * @return the value of task_file.file_id
     *
     * @mbg.generated
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_file.file_id
     *
     * @param fileId the value for task_file.file_id
     *
     * @mbg.generated
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }
}