package network.optimize.tool.entity;

public class TaskType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_type.task_type_name
     *
     * @mbg.generated
     */
    private String taskTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.id
     *
     * @return the value of task_type.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.id
     *
     * @param id the value for task_type.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_type.task_type_name
     *
     * @return the value of task_type.task_type_name
     *
     * @mbg.generated
     */
    public String getTaskTypeName() {
        return taskTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_type.task_type_name
     *
     * @param taskTypeName the value for task_type.task_type_name
     *
     * @mbg.generated
     */
    public void setTaskTypeName(String taskTypeName) {
        this.taskTypeName = taskTypeName;
    }
}